config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "home#index", as: :root
    resources :task, controller: 'task', :only => [:index, :create, :destroy, :edit, :update], path_names: {index: 'index'} do
      collection do
        patch "change_status"
      end
    end
  end

  unauthenticated :user do
    root to: "home#index_anonymous", as: :root_anonymous
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class DatetimeValidator < ActiveModel::Validator
    def validate(record)
        if record.due_date == nil
            record.errors[:base] << "Time and Date must be defined."
        elsif record.due_date < Time.current()
            record.errors[:base] << "Time and Date must be later then now."
        end
    end
end


class Task < ApplicationRecord
    belongs_to :user

    validates :title, length: {
        minimum: 5 }


    validates_with DatetimeValidator

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index_anonymous
  end

  def index

    if current_user.admin?
      @task = Task.all()
    else
      @task = Task.where(user_id: current_user.id)
    end
    if params[:term]
      @task = @task.where('title || description ILIKE ?', "%#{params[:term]}%")
    end
  
  end


  private

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :user_id, :term)
  end


end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  def index
    @task = Task.new()
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      flash[:success] = "Task created."
      redirect_to root_path
    else
      @error = @task.errors.full_messages
      render :index
    end
  end


  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.js
    end
  end

  def change_status
    @task = Task.find(params[:id])
    if @task.status == false
      @task.status = true
    else
      @task.status = false
    end
    @task.save()
    respond_to do |format|
      format.js
    end
  end

  def edit 
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
      if @task.update(task_params)
        redirect_to root_path()
      else 
        @error = @task.errors.full_messages
        render 'edit'
      end
  end


  private

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :user_id, :status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/home/index.html.erb
<div class="row columns">
    <div class="column is-10 is-offset-1">
        <div class="box card search">
            <%= form_tag(root_path, method: :get) do %>
                <div class="field has-addons">
                    <div class="control is-expanded">
                        <%= text_field_tag :term %>
                    </div>
                    <div class="control">
                        <%= submit_tag 'Search', class: "button is-medium is-black is-outlined"%>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>


<div class="row columns">
    <div class="column is-10 is-offset-1">
        <div class="card large">
            <div class="card-content">
                <div class="content">
                    <section class="page-title">
                        <!-- Container Start -->
                            <div class="row">
                                <div class="col-md-8 offset-md-2 text-center">
                                    <!-- Title text -->
                                    <div class="columns title_home">
                                        <div class="column"></div>
                                        <div class="column is-centered">
                                            <h3 class="title">Tasks</h3>
                                        </div>
                                        <div class="column new_task_button_home">
                                            <%= link_to task_index_path do %>
                	                            <div class="button is-outlined is-black is-medium button-new-task">New Task</div>
				                            <% end %>
                                        </div>
                                    </div>
                                    <hr class="task">
                                </div>
                            </div>
                        <!-- Container End -->
                    </section>

                    <section class="section content">
                            <div class="row">
                                <div class="col-lg-12 pt-5 pt-lg-0">
                                    <div class="about-content">
                                        <div class="task-undone">
                                            <% @task.each do |t| %>
                                                <% if t.status == false %>
                                                    <div class="row">
                                                        <div class="columns">
                                                            <div class="column options1">
                                                                <br><br><br>
                                                                <%= link_to task_path(t.id), method: :delete, remote: true, data: { confirm: 'Você tem certeza?' }, class: 'fas fa-trash-alt fa-2x button-delete' do %>
                                                                <% end %>
                                                                
                                                                

                                                                <%= link_to edit_task_path(:id => t.id), class: 'button-edit fas fa-edit fa-2x' do %>
                                                                <% end %>

                                                                <br>
                                                            </div>
                                                            <div class="column">
                                                                <br>
                                                                <p class="title_task"><%= t.title %></i></p> 
                                                                <p class="description_task"><%= t.description %></p>
                                                                <p class="datetime_task"><%= t.due_date %></p>

                                                                <br>
                                                            </div>
                                                            <div class="column options2">
                                                                <br><br>
                                                                <%= link_to change_status_task_index_path(:id => t.id), method: :patch, remote: true, class: 'button-done far fa-check-circle fa-5x' do %>
                                                                <% end %>
                                                                <br>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <% end %>
                                            <% end %>
                                        </div>
                                        <br>
                                        <hr class="task-done">
                                        <div class="task-done">
                                            <% @task.each do |t| %>
                                                <% if t.status == true %>
                                                    <div class="row">
                                                        <div class="columns">
                                                            <div class="column options1">
                                                                <br><br><br>
                                                                <%= link_to task_path(t.id), method: :delete, remote: true, data: { confirm: 'Você tem certeza?' }, class: 'fas fa-trash-alt fa-2x button-delete' do %>
                                                                <% end %>
                                                                
                                                                

                                                                <%= link_to edit_task_path(:id => t.id), class: 'button-edit fas fa-edit fa-2x' do %>
                                                                <% end %>

                                                                <br>
                                                            </div>
                                                            <div class="column">
                                                                <br>
                                                                <p class="title_task"><%= t.title %></i></p> 
                                                                <p class="description_task"><%= t.description %></p>
                                                                <p class="datetime_task"><%= t.due_date %></p>

                                                                <br>
                                                            </div>
                                                            <div class="column options2">
                                                                <br><br>
                                                                <%= link_to change_status_task_index_path(:id => t.id), method: :patch, remote: true, class: 'button-undone fas fa-times fa-5x' do %>
                                                                <% end %>

                                                                <br>
                                                            </div>
                                                        </div>
                                                    </div>
                                                <% end %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index_anonymous.html.erb
<div class="section">
    <div class="row columns">
        <div class="column is-10 is-offset-1">
            <div class="card large">
                <div class="card-content">
                    <div class="content">
                        <p>To use the service you need to login.</p>
                        <br>
                        <p>If you do not have an account yet, you can register for free.</p>
                        <br>
                        <%= link_to "REGISTER", new_user_registration_path, class: "button is-medium is-outlined is-black" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="/js/mobile_desktop_fullscreen.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    
  </head>

  <body style="width:100%;">
    <%= render "shared/navbar" %>
    <main>
      <section class="hero is-fullheight">
        <div class="hero-body has-text-centered is-mobile">
          <div class="container">
            <div id="flow">
              <span class="flow-1"></span>
              <span class="flow-2"></span>
              <span class="flow-3"></span>
            </div>
            <%= yield %>       
          </div>
        </div>

      </section>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- Footer Bottom -->
<footer class="footer-bottom" style="background-color: #222831">
  <!-- Container Start -->
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <!-- Copyright -->
        <div class="copyright">
          
          <p class="copyright">Copyright © 2019. All Rights Reserved</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Container End -->
  <!-- To Top -->
  <div class="top-to">
    <a id="top" class="" href="#"><i class="fa fa-angle-up"></i></a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav style="background-color:#0a1922;" class="columns is-mobile navbar is-fixed-top">
    <div class="column is-2-desktop logo">

    </div>

    <div class="column menu-button">
    <% if user_signed_in? %>
        <div class="dropdown is-hoverable is-pulled-right is-right">
            <div class="dropdown-trigger">
            <a class="icon is-large menu_icon" aria-haspopup="true" aria-controls="dropdown-menu">
                <i class="fa fa-bars fa-2x has-text-white-bis"></i>
            </a>
            </div>
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
            <div class="dropdown-content">
				<%= link_to root_path do %>
                	<p class="dropdown-item">Home</p>
				<% end %>
				<%= link_to task_index_path do %>
                	<p class="dropdown-item">New Task</p>
				<% end %>
				<%= link_to edit_user_registration_path do %>
                	<p class="dropdown-item">Profile</p>
				<% end %>
				
                <hr class="dropdown-divider">
				<%= link_to destroy_user_session_path, method: :delete do %>
                	<p class="dropdown-item">Logout</p>
				<% end %>
            </div>
            </div>
        </div>
        <% else %>
			<%= link_to new_user_session_path do %>
				<button class="button is-outlined is-pulled-right is-normal is-white login">Login</button> 
			<% end %>
                
        <% end %>
    </div>
</nav>

app/views/task/change_status.js.erb
$('.button-done').bind('ajax:success', function(){
    $(this).closest('.row').appendTo('.task-done')
    $(this).closest('.button-done').attr('class', 'button-undone fas fa-times fa-5x')

});

$('.button-undone').bind('ajax:success', function(){
    $(this).closest('.row').prependTo('.task-undone')
    $(this).closest('.button-undone').attr('class', 'button-done far fa-check-circle fa-5x')
});

app/views/task/destroy.js.erb
$('.button-delete').bind('ajax:success', function(){
    $(this).closest('div.row').fadeOut();
});

app/views/task/edit.html.erb
<div class="section">
  <div class="row columns">
    <div class="column is-10 is-offset-1">
      <div class="card large">
        <div class="card-content">
          <div class="content">
            <br><br>
            <center>
            <%= form_for @task, url: task_path(:id => @task.id) do |f| %>
              <% if @task.errors.any? %>
                <% @task.errors.full_messages.each do |m| %>
                    <p><%= m %></p>
                <% end %>
                <br><br>
              <% end %>
              <p>Title</p>
              <%= f.text_field :title %>
              <br><br><br><br>
              <p>Description</p>
              <%= f.text_field :description %>
              <br><br><br><br>
              <p>Date and Time</p>
              <%= f.datetime_field :due_date %>
              <br><br><br><br>
              <%= f.submit "Edit" %>
            <% end %>

            <br><br>
            </center>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/task/index.html.erb
<div class="section">
  <div class="row columns">
    <div class="column is-10 is-offset-1">
      <div class="card large">
        <div class="card-content">
          <div class="content">
            <br><br>
            <center>
            <%= form_for @task, url: task_index_path(@task) do |f| %>
              <% if @task.errors.any? %>
                <% @task.errors.full_messages.each do |m| %>
                  <p><%= m %></p>
                <% end %>
                <br><br>
              <% end %>
              <p>Title</p>
              <%= f.text_field :title %>
              <br><br><br><br>
              <p>Description</p>
              <%= f.text_field :description %>
              <br><br><br><br>
              <p>Date and Time</p>
              <%= f.datetime_field :due_date %>
              <br><br><br><br>
              <%= f.submit "Create" %>
            <% end %>

            <br><br>
            </center>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>